name: OneShotOneKill_${apiVersion}
version: '${version}'
main: de.oneshotonekill.OneShotOneKill
api-version: '${apiVersion}'
description: OneShotOneKill 1-Hit Kill Minigame Plugin built natively for Paper ${apiVersion} in Kotlin
author: Lostpold88
