name: OneShotOneKill_26.2
version: '1.0.0-26.2'
main: de.oneshotonekill.OneShotOneKill
api-version: '26.2'
description: OneShotOneKill 1-Hit Kill Minigame Plugin built natively for Paper 26.2
author: Lostpold88
